<Project Sdk="Remora.Resonite.Sdk/2.3.4">
  <PropertyGroup>
    <PackageId>BoundedUIX</PackageId>
    <Title>Bounded UIX</Title>
    <Authors>Banane9</Authors>
    <Version>2.1.2-beta</Version>
    <Description>This MonkeyLoader mod for Resonite makes UIX elements selectable and editable with the usual Slot gizmos,
as well as fixing UIX elements breaking when a parent is inserted.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ResoniteModdingGroup/BoundedUIX</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>mod; mods; monkeyloader; resonite; uix; development; developer; selection; tool; inspector</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
    <None Include="Locale\*" Pack="true" PackagePath="content/Locale/" />
  </ItemGroup>

  <ItemGroup>
    <ResoniteReference Include="Elements.Core" />
    <ResoniteReference Include="FrooxEngine" />
  </ItemGroup>
</Project>